apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o wert
    kompose.version: 1.27.0 (HEAD)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o wert
        kompose.version: 1.27.0 (HEAD)
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: server
    spec:
      containers:
        - args:
            - npm
            - run
            - server
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: env
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
          image: 781017761620.dkr.ecr.us-east-1.amazonaws.com/mern-repo:backend-build-18
          name: backend-srv
          ports:
            - containerPort: 5000
      imagePullSecrets:
          - name: regcred
